-- 1. Create stores table
CREATE TABLE IF NOT EXISTS public.stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert 3 default stores (if not exist)
INSERT INTO public.stores (id, name, address)
VALUES 
    (1, 'Condet', 'Toko Condet'),
    (2, 'Rawabelong', 'Toko Rawabelong'),
    (3, 'Tangerang', 'Toko Tangerang')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

-- 2. Create bibit_stocks table
CREATE TABLE IF NOT EXISTS public.bibit_stocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bibit_id BIGINT REFERENCES public.bibit(id) ON DELETE CASCADE,
    store_id BIGINT REFERENCES public.stores(id) ON DELETE CASCADE,
    bottle_size INTEGER NOT NULL, -- 500 or 1000
    sealed_bottles_qty INTEGER DEFAULT 0,
    opened_bottle_ml INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(bibit_id, store_id, bottle_size)
);

-- 3. Create bottle_stocks table
CREATE TABLE IF NOT EXISTS public.bottle_stocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bottle_id BIGINT REFERENCES public.bottles(id) ON DELETE CASCADE,
    store_id BIGINT REFERENCES public.stores(id) ON DELETE CASCADE,
    stock_qty INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(bottle_id, store_id)
);

-- Migrate existing bottles stock to store 1 (Condet)
INSERT INTO public.bottle_stocks (bottle_id, store_id, stock_qty)
SELECT id, 1, COALESCE(stock, 0) FROM public.bottles
ON CONFLICT (bottle_id, store_id) DO NOTHING;

-- 4. Create product_stocks table
CREATE TABLE IF NOT EXISTS public.product_stocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfume_size_id BIGINT REFERENCES public.perfume_sizes(id) ON DELETE CASCADE,
    store_id BIGINT REFERENCES public.stores(id) ON DELETE CASCADE,
    stock_qty INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(perfume_size_id, store_id)
);

-- Migrate existing perfume sizes stock to store 1 (Condet)
INSERT INTO public.product_stocks (perfume_size_id, store_id, stock_qty)
SELECT id, 1, COALESCE(stock, 0) FROM public.perfume_sizes
ON CONFLICT (perfume_size_id, store_id) DO NOTHING;

-- Create function for updating timestamps if it doesn't exist
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply triggers
DROP TRIGGER IF EXISTS update_stores_modtime ON public.stores;
CREATE TRIGGER update_stores_modtime BEFORE UPDATE ON public.stores
FOR EACH ROW EXECUTE FUNCTION update_modified_column();

DROP TRIGGER IF EXISTS update_bibit_stocks_modtime ON public.bibit_stocks;
CREATE TRIGGER update_bibit_stocks_modtime BEFORE UPDATE ON public.bibit_stocks
FOR EACH ROW EXECUTE FUNCTION update_modified_column();

DROP TRIGGER IF EXISTS update_bottle_stocks_modtime ON public.bottle_stocks;
CREATE TRIGGER update_bottle_stocks_modtime BEFORE UPDATE ON public.bottle_stocks
FOR EACH ROW EXECUTE FUNCTION update_modified_column();

DROP TRIGGER IF EXISTS update_product_stocks_modtime ON public.product_stocks;
CREATE TRIGGER update_product_stocks_modtime BEFORE UPDATE ON public.product_stocks
FOR EACH ROW EXECUTE FUNCTION update_modified_column();
